// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export const components = {
  "Alert": {
    "type": "COMPONENT",
    "id": "Alert",
    "title": "Alert",
    "propsConfig": {
      "type": "object",
      "required": [],
      "className": "AlertProps",
      "properties": {
        "kind": {
          "type": "string",
          "enum": [
            "info",
            "positive",
            "negative",
            "warning"
          ],
          "description": "Alert 的类型",
          "tags": {
            "description": "Alert 的类型",
            "default": "'info'"
          },
          "default": "info"
        },
        "children": {
          "type": "reactNode",
          "className": "ReactNode",
          "description": "React Node",
          "tags": {
            "description": "React Node",
            "default": "null"
          },
          "default": null
        }
      }
    }
  }
};
